name: TKRubberPageControlDemo

options:
  bundleIdPrefix: com.tbxark
  deploymentTarget:
    iOS: "13.0"
  createIntermediateGroups: true
  groupSortPosition: top

packages:
  TKRubberPageControl:
    path: ..

targets:
  TKRubberPageControlDemo:
    type: application
    platform: iOS

    sources:
      - path: Sources

    resources:
      - path: Resources

    dependencies:
      - package: TKRubberPageControl
        product: TKRubberPageControl

    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: RubberPageControl
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tbxark.tkrubberpagecontrol.demo
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
